server {
    listen 80;
    server_name _; # Mettez l'adresse IP de votre serveur ici si vous la connaissez
    root /var/www/e-CRE/public; # Assurez-vous que le chemin vers votre projet est correct

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;

    charset utf-8;

    # Limite de taille pour les uploads (PDF, Excel, Word) et les en-têtes Inertia
    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    # Liaison avec votre PHP 8.5.4
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}