server {
    listen 80;
    server_name _; # Mettez l'adresse IP de votre serveur ici si vous la connaissez
    root /var/www/e-CRE/public; # Assurez-vous que le chemin vers votre projet est correct

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;

    charset utf-8;

    # Limite de taille pour les uploads (PDF, Excel, Word) et les en-têtes Inertia
    client_max_body_size 20M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    # Liaison avec votre PHP 8.3.x
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}




# installation CloudFlare
# Add cloudflare gpg key
sudo mkdir -p --mode=0755 /usr/share/keyrings
curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

# Add this repo to your apt repositories
echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' | sudo tee /etc/apt/sources.list.d/cloudflared.list

# install cloudflared
sudo apt-get update && sudo apt-get install cloudflared



#Installation en tant que service
sudo cloudflared service install eyJhIjoiMWRiOTI2MzZlNjEyODBhOGMyNDRjY2ZmOWU4NTg1YWUiLCJ0IjoiYzk1MDQyMTktOTQzNS00ZTgyLWE4MmMtYjM4YjBjZWZlNGM1IiwicyI6IlptSTBPREJtWkdFdE1qZGpNeTAwTm1GaUxUZ3dOamd0TVdWaE1EY3haR0k0TmpFeCJ9